[tool.black]
line-length = 120
target-version = ["py38", "py39"]

[tool.isort]
profile = "black"
multi_line_output = 3
extend_skip = ["env/**", "venv/**", ".pytest_cache/**"]
line_length = 110
skip_gitignore = true
